[package]
name = "bricklayers_wasm"
version = "1.0.0"
edition = "2021"
description = "BrickLayers algorithm compiled to WASI"
license = "LGPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.13"

[build-dependencies]
prost-build = "0.13"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.