# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/slots/handshake/v0/handshake.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/slots/handshake/v0/handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cura.plugins.v0 import slot_id_pb2 as cura_dot_plugins_dot_v0_dot_slot__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cura/plugins/slots/handshake/v0/handshake.proto\x12\x1f\x63ura.plugins.slots.handshake.v0\x1a\x1d\x63ura/plugins/v0/slot_id.proto\"u\n\x0b\x43\x61llRequest\x12(\n\x07slot_id\x18\x01 \x01(\x0e\x32\x17.cura.plugins.v0.SlotID\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0bplugin_name\x18\x03 \x01(\t\x12\x16\n\x0eplugin_version\x18\x04 \x01(\t\"\x91\x01\n\x0c\x43\x61llResponse\x12\x1a\n\x12slot_version_range\x18\x01 \x01(\t\x12\x13\n\x0bplugin_name\x18\x02 \x01(\t\x12\x16\n\x0eplugin_version\x18\x03 \x01(\t\x12\x38\n\x17\x62roadcast_subscriptions\x18\x04 \x03(\x0e\x32\x17.cura.plugins.v0.SlotID2y\n\x10HandshakeService\x12\x65\n\x04\x43\x61ll\x12,.cura.plugins.slots.handshake.v0.CallRequest\x1a-.cura.plugins.slots.handshake.v0.CallResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.slots.handshake.v0.handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLREQUEST']._serialized_start=115
  _globals['_CALLREQUEST']._serialized_end=232
  _globals['_CALLRESPONSE']._serialized_start=235
  _globals['_CALLRESPONSE']._serialized_end=380
  _globals['_HANDSHAKESERVICE']._serialized_start=382
  _globals['_HANDSHAKESERVICE']._serialized_end=503
# @@protoc_insertion_point(module_scope)
