# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/v0/gcode_path.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/v0/gcode_path.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cura.plugins.v0 import polygons_pb2 as cura_dot_plugins_dot_v0_dot_polygons__pb2
from cura.plugins.v0 import printfeatures_pb2 as cura_dot_plugins_dot_v0_dot_printfeatures__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n cura/plugins/v0/gcode_path.proto\x12\x0f\x63ura.plugins.v0\x1a\x1e\x63ura/plugins/v0/polygons.proto\x1a#cura/plugins/v0/printfeatures.proto\"H\n\x10SpeedDerivatives\x12\x10\n\x08velocity\x18\x01 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x01\x12\x0c\n\x04jerk\x18\x03 \x01(\x01\"\x9b\x05\n\tGCodePath\x12\'\n\x04path\x18\x01 \x01(\x0b\x32\x19.cura.plugins.v0.OpenPath\x12\x37\n\x0fspace_fill_type\x18\x02 \x01(\x0e\x32\x1e.cura.plugins.v0.SpaceFillType\x12\x0c\n\x04\x66low\x18\x03 \x01(\x01\x12\x14\n\x0cwidth_factor\x18\x04 \x01(\x01\x12\x11\n\tspiralize\x18\x05 \x01(\x08\x12\x14\n\x0cspeed_factor\x18\x06 \x01(\x01\x12\"\n\x1aspeed_back_pressure_factor\x18\x07 \x01(\x01\x12\x0f\n\x07retract\x18\x08 \x01(\x08\x12)\n!unretract_before_last_travel_move\x18\t \x01(\x08\x12\x15\n\rperform_z_hop\x18\n \x01(\x08\x12\x15\n\rperform_prime\x18\x0b \x01(\x08\x12!\n\x19skip_agressive_merge_hint\x18\x0c \x01(\x08\x12\x0c\n\x04\x64one\x18\r \x01(\x08\x12\x11\n\tfan_speed\x18\x0e \x01(\x01\x12\x11\n\tmesh_name\x18\x0f \x01(\t\x12.\n\x07\x66\x65\x61ture\x18\x10 \x01(\x0e\x32\x1d.cura.plugins.v0.PrintFeature\x12<\n\x11speed_derivatives\x18\x11 \x01(\x0b\x32!.cura.plugins.v0.SpeedDerivatives\x12\x12\n\nline_width\x18\x12 \x01(\x03\x12\x17\n\x0flayer_thickness\x18\x13 \x01(\x03\x12\x12\n\nflow_ratio\x18\x14 \x01(\x01\x12\x16\n\x0eis_bridge_path\x18\x15 \x01(\x08\x12\x10\n\x08z_offset\x18\x16 \x01(\x03\x12!\n\x19retract_for_nozzle_switch\x18\x17 \x01(\x08*\\\n\rSpaceFillType\x12\x13\n\x0fNONE_SPACE_FILL\x10\x00\x12\x11\n\rPOLYGONS_FILL\x10\x01\x12\x13\n\x0fPOLY_LINES_FILL\x10\x02\x12\x0e\n\nLINES_FILL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.v0.gcode_path_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPACEFILLTYPE']._serialized_start=866
  _globals['_SPACEFILLTYPE']._serialized_end=958
  _globals['_SPEEDDERIVATIVES']._serialized_start=122
  _globals['_SPEEDDERIVATIVES']._serialized_end=194
  _globals['_GCODEPATH']._serialized_start=197
  _globals['_GCODEPATH']._serialized_end=864
# @@protoc_insertion_point(module_scope)
