# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/v0/polygons.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/v0/polygons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cura.plugins.v0 import point3d_pb2 as cura_dot_plugins_dot_v0_dot_point3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ura/plugins/v0/polygons.proto\x12\x0f\x63ura.plugins.v0\x1a\x1d\x63ura/plugins/v0/point3d.proto\"2\n\x08OpenPath\x12&\n\x04path\x18\x01 \x03(\x0b\x32\x18.cura.plugins.v0.Point3D\"5\n\tOpenPaths\x12(\n\x05paths\x18\x01 \x03(\x0b\x32\x19.cura.plugins.v0.OpenPath\"4\n\nClosedPath\x12&\n\x04path\x18\x01 \x03(\x0b\x32\x18.cura.plugins.v0.Point3D\"4\n\nFilledPath\x12&\n\x04path\x18\x01 \x03(\x0b\x32\x18.cura.plugins.v0.Point3D\"c\n\x07Polygon\x12,\n\x07outline\x18\x01 \x01(\x0b\x32\x1b.cura.plugins.v0.FilledPath\x12*\n\x05holes\x18\x02 \x03(\x0b\x32\x1b.cura.plugins.v0.FilledPath\"6\n\x08Polygons\x12*\n\x08polygons\x18\x01 \x03(\x0b\x32\x18.cura.plugins.v0.Polygonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.v0.polygons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENPATH']._serialized_start=82
  _globals['_OPENPATH']._serialized_end=132
  _globals['_OPENPATHS']._serialized_start=134
  _globals['_OPENPATHS']._serialized_end=187
  _globals['_CLOSEDPATH']._serialized_start=189
  _globals['_CLOSEDPATH']._serialized_end=241
  _globals['_FILLEDPATH']._serialized_start=243
  _globals['_FILLEDPATH']._serialized_end=295
  _globals['_POLYGON']._serialized_start=297
  _globals['_POLYGON']._serialized_end=396
  _globals['_POLYGONS']._serialized_start=398
  _globals['_POLYGONS']._serialized_end=452
# @@protoc_insertion_point(module_scope)
