# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/v0/slot_id.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/v0/slot_id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63ura/plugins/v0/slot_id.proto\x12\x0f\x63ura.plugins.v0*\xa5\x01\n\x06SlotID\x12\x16\n\x12SETTINGS_BROADCAST\x10\x00\x12\x13\n\x0fSIMPLIFY_MODIFY\x10\x64\x12\x16\n\x12POSTPROCESS_MODIFY\x10\x65\x12\x11\n\rINFILL_MODIFY\x10\x66\x12\x16\n\x12GCODE_PATHS_MODIFY\x10g\x12\x14\n\x0fINFILL_GENERATE\x10\xc8\x01\x12\x15\n\x10\x44IALECT_GENERATE\x10\xc9\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.v0.slot_id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLOTID']._serialized_start=51
  _globals['_SLOTID']._serialized_end=216
# @@protoc_insertion_point(module_scope)
