# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/slots/broadcast/v0/broadcast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/slots/broadcast/v0/broadcast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/cura/plugins/slots/broadcast/v0/broadcast.proto\x12\x1f\x63ura.plugins.slots.broadcast.v0\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n\x08Settings\x12I\n\x08settings\x18\x01 \x03(\x0b\x32\x37.cura.plugins.slots.broadcast.v0.Settings.SettingsEntry\x1a/\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x99\x03\n\x1f\x42roadcastServiceSettingsRequest\x12\x42\n\x0fglobal_settings\x18\x01 \x01(\x0b\x32).cura.plugins.slots.broadcast.v0.Settings\x12\x44\n\x11\x65xtruder_settings\x18\x02 \x03(\x0b\x32).cura.plugins.slots.broadcast.v0.Settings\x12\x42\n\x0fobject_settings\x18\x03 \x03(\x0b\x32).cura.plugins.slots.broadcast.v0.Settings\x12p\n\x11limit_to_extruder\x18\x04 \x03(\x0b\x32U.cura.plugins.slots.broadcast.v0.BroadcastServiceSettingsRequest.LimitToExtruderEntry\x1a\x36\n\x14LimitToExtruderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x32\x83\x01\n\x10\x42roadcastService\x12o\n\x11\x42roadcastSettings\x12@.cura.plugins.slots.broadcast.v0.BroadcastServiceSettingsRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.slots.broadcast.v0.broadcast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTINGS_SETTINGSENTRY']._loaded_options = None
  _globals['_SETTINGS_SETTINGSENTRY']._serialized_options = b'8\001'
  _globals['_BROADCASTSERVICESETTINGSREQUEST_LIMITTOEXTRUDERENTRY']._loaded_options = None
  _globals['_BROADCASTSERVICESETTINGSREQUEST_LIMITTOEXTRUDERENTRY']._serialized_options = b'8\001'
  _globals['_SETTINGS']._serialized_start=114
  _globals['_SETTINGS']._serialized_end=248
  _globals['_SETTINGS_SETTINGSENTRY']._serialized_start=201
  _globals['_SETTINGS_SETTINGSENTRY']._serialized_end=248
  _globals['_BROADCASTSERVICESETTINGSREQUEST']._serialized_start=251
  _globals['_BROADCASTSERVICESETTINGSREQUEST']._serialized_end=660
  _globals['_BROADCASTSERVICESETTINGSREQUEST_LIMITTOEXTRUDERENTRY']._serialized_start=606
  _globals['_BROADCASTSERVICESETTINGSREQUEST_LIMITTOEXTRUDERENTRY']._serialized_end=660
  _globals['_BROADCASTSERVICE']._serialized_start=663
  _globals['_BROADCASTSERVICE']._serialized_end=794
# @@protoc_insertion_point(module_scope)
