# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cura/plugins/v0/printfeatures.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cura/plugins/v0/printfeatures.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#cura/plugins/v0/printfeatures.proto\x12\x0f\x63ura.plugins.v0*\xbb\x02\n\x0cPrintFeature\x12\x0c\n\x08NONETYPE\x10\x00\x12\r\n\tOUTERWALL\x10\x01\x12\r\n\tINNERWALL\x10\x02\x12\x08\n\x04SKIN\x10\x03\x12\x0b\n\x07SUPPORT\x10\x04\x12\r\n\tSKIRTBRIM\x10\x05\x12\n\n\x06INFILL\x10\x06\x12\x11\n\rSUPPORTINFILL\x10\x07\x12\x13\n\x0fMOVEUNRETRACTED\x10\x08\x12\x11\n\rMOVERETRACTED\x10\t\x12\x14\n\x10SUPPORTINTERFACE\x10\n\x12\x0e\n\nPRIMETOWER\x10\x0b\x12\x17\n\x13MOVEWHILERETRACTING\x10\x0c\x12\x19\n\x15MOVEWHILEUNRETRACTING\x10\r\x12\x1e\n\x1aSTATIONARYRETRACTUNRETRACT\x10\x0e\x12\x18\n\x14NUMPRINTFEATURETYPES\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cura.plugins.v0.printfeatures_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRINTFEATURE']._serialized_start=57
  _globals['_PRINTFEATURE']._serialized_end=372
# @@protoc_insertion_point(module_scope)
